#!/usr/bin/env python3
"""Generate the static roofline SVG for doc/performance_dtln.md, parsing
analysis/roofline_log.txt instead of hardcoding the data points -- unlike
the sibling gemm project's script/gen_roofline_svg.py (which hand-codes a
SERIES/POINTS table refreshed by copy-paste after each sweep), this one
reads script/4_roofline_report.py's own output directly, so re-running
that report and this script back-to-back always plots the current numbers
with no manual transcription step.

No external deps (pure stdlib `math` + string building), same reasoning
as the gemm version: renders inline on GitHub as a plain image, no
matplotlib/cairosvg needed, dependency-free for anyone re-running this
later.

Usage:
  python3 /home/ajno5/work/2_pattern/tflm/script/5_gen_roofline_svg.py
  python3 /home/ajno5/work/2_pattern/tflm/script/5_gen_roofline_svg.py \\
      --log /path/to/other_roofline_log.txt --out /path/to/out.svg

To refresh after a new run: `python3 script/4_roofline_report.py` (writes
analysis/roofline_log.txt), then this script -- no data to hand-edit.
"""
import argparse
import math
import os
import re
import sys
from collections import defaultdict

PROJECT_ROOT = "/home/ajno5/work/2_pattern/tflm"
DEFAULT_LOG = os.path.join(PROJECT_ROOT, "analysis", "roofline_log.txt")
DEFAULT_OUT = os.path.join(PROJECT_ROOT, "doc", "dtln_roofline.svg")

TABLE_ROW_RE = re.compile(r"^\|(.+)\|\s*$")


# ---------------------------------------------------------------------------
# Parse analysis/roofline_log.txt (script/4_roofline_report.py's output).
# ---------------------------------------------------------------------------


def parse_cell(s):
    s = s.strip()
    return s


def parse_table(lines, start_idx):
    """lines[start_idx] is the table's header row ('| col | col | ... |').
    Returns (header_cells, data_rows, next_idx) -- next_idx is the line
    index right after the last row of this table."""
    header = [parse_cell(c) for c in lines[start_idx].strip().strip("|").split("|")]
    i = start_idx + 1
    if i < len(lines) and set(lines[i].strip()) <= set("|-: "):
        i += 1  # skip the '|---|---|' separator row
    rows = []
    while i < len(lines) and TABLE_ROW_RE.match(lines[i]):
        cells = [parse_cell(c) for c in lines[i].strip().strip("|").split("|")]
        rows.append(dict(zip(header, cells)))
        i += 1
    return rows, i


def clean_number(s):
    """'0.05%' -> 0.05, '1,234.56' -> 1234.56, '`FULLY_CONNECTED`' -> FULLY_CONNECTED (non-numeric passthrough)."""
    s = s.strip().strip("`")
    t = s.replace(",", "").rstrip("%")
    try:
        return float(t)
    except ValueError:
        return s


def parse_report(log_path):
    with open(log_path) as f:
        lines = f.read().splitlines()

    meta = {}
    m = re.search(r"peak BW ([\d.]+) GB/s", "\n".join(lines))
    if m:
        meta["peak_bw_gbps"] = float(m.group(1))
    m = re.search(r"idealized peak compute ([\d.]+) GFLOP/s", "\n".join(lines))
    if m:
        meta["peak_compute_gflops"] = float(m.group(1))
    m = re.search(r"ridge point ([\d.]+) FLOP/byte", "\n".join(lines))
    if m:
        meta["ridge_point"] = float(m.group(1))
    m = re.search(r"Empirical compute-roof ceiling: ([\d.]+) GFLOP/s", "\n".join(lines))
    if m:
        meta["ceiling_gflops"] = float(m.group(1))

    ai_rows, perf_rows = [], []
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("### Arithmetic intensity"):
            j = i + 1
            while j < len(lines) and not lines[j].startswith("|"):
                j += 1
            ai_rows, i = parse_table(lines, j)
            continue
        if line.startswith("### Achieved performance"):
            j = i + 1
            while j < len(lines) and not lines[j].startswith("|"):
                j += 1
            perf_rows, i = parse_table(lines, j)
            continue
        i += 1

    if not meta or not ai_rows or not perf_rows:
        sys.exit(
            f"error: couldn't find expected sections in {log_path} -- "
            "was it generated by script/4_roofline_report.py?"
        )
    return meta, ai_rows, perf_rows


def build_points(ai_rows, perf_rows):
    """Join the two tables on (op, call) -> [(op, call, variant, ai, gflops), ...]."""
    ai_by_key = {}
    for row in ai_rows:
        key = (row["op"].strip("`"), row["call"])
        ai = clean_number(row["AI (FLOP/byte)"].split()[0])  # "2.00 (memory-bound)" -> 2.00
        ai_by_key[key] = ai

    points = []
    for row in perf_rows:
        key = (row["op"].strip("`"), row["call"])
        if key not in ai_by_key:
            continue  # e.g. LOGISTIC -- no FLOP model, not plottable
        p_mflops = clean_number(row["P (MFLOP/s)"])
        if not isinstance(p_mflops, float):
            continue  # "n/a (no FLOP model for this op)"
        points.append({
            "op": key[0],
            "call": key[1],
            "variant": row["variant"],
            "ai": ai_by_key[key],
            "gflops": p_mflops / 1000.0,
        })
    return points


# ---------------------------------------------------------------------------
# SVG rendering.
# ---------------------------------------------------------------------------

VARIANT_COLORS = {
    "scalar": "#c9433a",
    "vectorized": "#1baf7a",
}

# Marker shape identifies the op (color already identifies scalar/vectorized).
OP_MARKERS = {
    "FULLY_CONNECTED": "circle",
    "UNIDIRECTIONAL_SEQUENCE_LSTM": None,  # assigned per call below (diamond/square)
}


def op_call_label(op, call):
    if op == "FULLY_CONNECTED":
        return "FULLY_CONNECTED"
    return f"LSTM (call {call})"


def op_call_marker(op, call):
    if op == "FULLY_CONNECTED":
        return "circle"
    return "diamond" if call == "1" else "square"


def marker_svg(shape, cx, cy, color, r=7):
    if shape == "diamond":
        rr = r + 1
        pts = f"{cx:.1f},{cy-rr:.1f} {cx+rr:.1f},{cy:.1f} {cx:.1f},{cy+rr:.1f} {cx-rr:.1f},{cy:.1f}"
        return f'<polygon points="{pts}" fill="{color}" stroke="#ffffff" stroke-width="1.5"/>'
    elif shape == "square":
        s = r * 1.6
        return (f'<rect x="{cx-s/2:.1f}" y="{cy-s/2:.1f}" width="{s:.1f}" height="{s:.1f}" '
                f'fill="{color}" stroke="#ffffff" stroke-width="1.5"/>')
    else:
        return f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r}" fill="{color}" stroke="#ffffff" stroke-width="1.5" opacity="0.85"/>'


JITTER_PX = 9


def compute_x_jitter(points):
    """dtln's FULLY_CONNECTED and both UNIDIRECTIONAL_SEQUENCE_LSTM calls
    all land at exactly the same AI (2.00 FLOP/byte -- see
    doc/performance_dtln.md's "Arithmetic intensity" table, not a
    coincidence: every one of these is a batch-1 int8 GEMV with zero
    weight reuse). Plotted at their true x they'd stack directly on top of
    each other and the later-drawn marker would fully hide the earlier one
    regardless of transparency, since their y values (achieved GFLOP/s) are
    also close. Nudges each op a few px apart horizontally so all three
    stay visible -- {(op, call): x_offset_px, ...}, deterministic by
    (op, call) sort order so it's stable across runs."""
    by_opcall_ai = {}
    for p in points:
        by_opcall_ai[(p["op"], p["call"])] = p["ai"]

    buckets = defaultdict(list)
    for key, ai in by_opcall_ai.items():
        buckets[round(ai, 6)].append(key)

    jitter = {}
    for ai, keys in buckets.items():
        keys = sorted(keys)
        n = len(keys)
        for idx, key in enumerate(keys):
            jitter[key] = (idx - (n - 1) / 2) * JITTER_PX
    return jitter


def render_svg(meta, points):
    W = 900
    ML, MR, MT = 78, 210, 40
    plotW, plotH = W - ML - MR, 440
    axisBottom = MT + plotH
    tickLabelY = axisBottom + 20
    axisTitleY = axisBottom + 40
    legend1Y = axisBottom + 65
    legend2Y = axisBottom + 90
    footnoteY = axisBottom + 114
    footnote2Y = footnoteY + 16
    H = footnote2Y + 16

    peak_bw = meta.get("peak_bw_gbps")
    ridge_idealized = meta.get("ridge_point")
    # The ridge point that actually matters for this project: where the
    # memory roof crosses the *measured* FU ceiling, not the idealized
    # peak-compute one -- everything left of it is memory-bound even
    # against what this CPU can genuinely sustain, which is the number
    # doc/gem5_integration.md treats as authoritative.
    ridge_measured = (
        meta["ceiling_gflops"] / peak_bw if peak_bw and meta.get("ceiling_gflops") else None
    )

    ais = [p["ai"] for p in points]
    x_of_interest = ais + [v for v in (ridge_idealized, ridge_measured) if v]
    gs = [p["gflops"] for p in points] + [meta["ceiling_gflops"]]
    x_lo = min(0.5, min(x_of_interest) / 2) if x_of_interest else 0.5
    x_hi = max(5.0, max(x_of_interest, default=10) * 2)
    y_lo = min(0.03, min(gs) / 3) if gs else 0.03
    y_hi = max(meta.get("peak_compute_gflops", 128) * 2, max(gs) * 3)

    x_dom = (x_lo, x_hi)
    y_dom = (y_lo, y_hi)
    lx, rx = math.log10(x_dom[0]), math.log10(x_dom[1])
    ly, ry = math.log10(y_dom[0]), math.log10(y_dom[1])

    def px(ai):
        return ML + (math.log10(ai) - lx) / (rx - lx) * plotW

    def py(g):
        return MT + plotH - (math.log10(g) - ly) / (ry - ly) * plotH

    def log_ticks(lo, hi):
        ticks = []
        e = math.floor(math.log10(lo))
        while 10 ** e <= hi * 1.001:
            for m in (1, 2, 3, 5):
                v = m * 10 ** e
                if lo * 0.999 <= v <= hi * 1.001:
                    ticks.append(round(v, 6))
            e += 1
        return ticks

    x_ticks = log_ticks(*x_dom)
    y_ticks = log_ticks(*y_dom)

    TEXT_MUTED = "#767671"
    TEXT_SEC = "#3d3d3a"
    TEXT_PRI = "#111111"
    GRID = "#e4e3dd"
    AXIS = "#b9b8b1"

    svg = []
    svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" font-family="Helvetica, Arial, sans-serif">')
    svg.append(f'<rect x="0" y="0" width="{W}" height="{H}" fill="#ffffff"/>')
    svg.append(f'<text x="{ML}" y="22" font-size="15" fill="{TEXT_PRI}" font-weight="700">dtln roofline: scalar vs. vectorized vs. measured FU ceiling</text>')

    for v in x_ticks:
        x = px(v)
        svg.append(f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{MT+plotH}" stroke="{GRID}" stroke-width="1"/>')
        label = f"{v:g}"
        svg.append(f'<text x="{x:.1f}" y="{tickLabelY}" font-size="12" fill="{TEXT_MUTED}" text-anchor="middle">{label}</text>')
    for v in y_ticks:
        y = py(v)
        svg.append(f'<line x1="{ML}" y1="{y:.1f}" x2="{ML+plotW}" y2="{y:.1f}" stroke="{GRID}" stroke-width="1"/>')
        label = f"{v:g}"
        svg.append(f'<text x="{ML-10}" y="{y+4:.1f}" font-size="12" fill="{TEXT_MUTED}" text-anchor="end">{label}</text>')

    svg.append(f'<line x1="{ML}" y1="{MT+plotH}" x2="{ML+plotW}" y2="{MT+plotH}" stroke="{AXIS}" stroke-width="1"/>')
    svg.append(f'<line x1="{ML}" y1="{MT}" x2="{ML}" y2="{MT+plotH}" stroke="{AXIS}" stroke-width="1"/>')

    svg.append(f'<text x="{ML+plotW/2:.1f}" y="{axisTitleY}" font-size="13" fill="{TEXT_SEC}" text-anchor="middle">Arithmetic intensity (FLOP / byte, log scale)</text>')
    svg.append(f'<text x="20" y="{MT+plotH/2:.1f}" font-size="13" fill="{TEXT_SEC}" text-anchor="middle" transform="rotate(-90 20 {MT+plotH/2:.1f})">Achieved performance (GFLOP/s, log scale)</text>')

    # memory-bound roof: g = peak_bw * ai
    if peak_bw:
        x1 = x_dom[0]
        x2 = min(x_dom[1], y_dom[1] / peak_bw)
        if x2 > x1:
            svg.append(f'<line x1="{px(x1):.1f}" y1="{py(peak_bw*x1):.1f}" x2="{px(x2):.1f}" y2="{py(peak_bw*x2):.1f}" '
                       f'stroke="{TEXT_MUTED}" stroke-width="2" stroke-dasharray="5 4"/>')
            svg.append(f'<text x="{px(x2)-6:.1f}" y="{py(peak_bw*x2)-8:.1f}" font-size="11.5" fill="{TEXT_SEC}" text-anchor="end">memory roof ({peak_bw} GB/s)</text>')

    # Ridge point vs. the *measured* FU ceiling -- drawn first (so it's
    # underneath, giving it visual priority isn't needed) but styled bold
    # and blue to match the measured-ceiling line: this is the ridge point
    # that actually matters for this project (see doc/gem5_integration.md
    # -- the idealized 128 GFLOP/s figure was the wrong ceiling to begin
    # with). Left of it, an op is memory-bound even against what this CPU
    # can genuinely sustain, not just against a too-optimistic ideal.
    if ridge_measured and x_dom[0] <= ridge_measured <= x_dom[1]:
        x = px(ridge_measured)
        svg.append(f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{MT+plotH}" stroke="#2a78d6" '
                   f'stroke-width="2" stroke-dasharray="1 4"/>')
        svg.append(f'<text x="{x+6:.1f}" y="{axisBottom-8}" font-size="11.5" fill="#2a78d6" font-weight="700">ridge (measured), {ridge_measured:.2f} FLOP/byte</text>')

    # Ridge point vs. the idealized peak-compute roof -- kept for contrast,
    # styled muted/secondary (same idealized-vs-measured distinction as the
    # two roof lines below).
    if ridge_idealized and x_dom[0] <= ridge_idealized <= x_dom[1]:
        x = px(ridge_idealized)
        svg.append(f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{MT+plotH}" stroke="{AXIS}" '
                   f'stroke-width="1.5" stroke-dasharray="1 4"/>')
        svg.append(f'<text x="{x+6:.1f}" y="{MT+14}" font-size="11" fill="{TEXT_MUTED}">ridge (idealized), {ridge_idealized:g} FLOP/byte</text>')

    # idealized peak-compute roof (the naive, too-optimistic ceiling -- kept for contrast)
    peak_compute = meta.get("peak_compute_gflops")
    if peak_compute and y_dom[0] <= peak_compute <= y_dom[1]:
        y = py(peak_compute)
        svg.append(f'<line x1="{ML}" y1="{y:.1f}" x2="{ML+plotW}" y2="{y:.1f}" stroke="{AXIS}" '
                   f'stroke-width="1.5" stroke-dasharray="2 5" opacity="0.8"/>')
        svg.append(f'<text x="{ML+plotW+8}" y="{y+4:.1f}" font-size="11" fill="{TEXT_MUTED}">idealized {peak_compute:g} GFLOP/s</text>')

    # empirically-measured FU ceiling (the real, authoritative one)
    ceiling = meta.get("ceiling_gflops")
    if ceiling and y_dom[0] <= ceiling <= y_dom[1]:
        y = py(ceiling)
        svg.append(f'<line x1="{ML}" y1="{y:.1f}" x2="{ML+plotW}" y2="{y:.1f}" stroke="#2a78d6" '
                   f'stroke-width="2.5" stroke-dasharray="2 4"/>')
        svg.append(f'<text x="{ML+plotW+8}" y="{y+4:.1f}" font-size="11.5" fill="#2a78d6" font-weight="700">{ceiling:g} GFLOP/s measured</text>')

    # scatter points
    jitter = compute_x_jitter(points)
    for p in points:
        cx = px(p["ai"]) + jitter.get((p["op"], p["call"]), 0)
        cy = py(p["gflops"])
        color = VARIANT_COLORS.get(p["variant"], TEXT_MUTED)
        shape = op_call_marker(p["op"], p["call"])
        svg.append(marker_svg(shape, cx, cy, color))

    # legend: variant (color)
    leg_y, leg_x = legend1Y, ML
    for variant, color in VARIANT_COLORS.items():
        svg.append(f'<rect x="{leg_x}" y="{leg_y-10}" width="12" height="12" rx="3" fill="{color}"/>')
        svg.append(f'<text x="{leg_x+17}" y="{leg_y}" font-size="12" fill="{TEXT_SEC}">{variant}</text>')
        leg_x += 17 + 8 * len(variant) + 26
    svg.append(f'<line x1="{leg_x}" y1="{leg_y-5}" x2="{leg_x+20}" y2="{leg_y-5}" stroke="{TEXT_MUTED}" stroke-width="2" stroke-dasharray="4 3"/>')
    svg.append(f'<text x="{leg_x+26}" y="{leg_y}" font-size="12" fill="{TEXT_SEC}">Memory roof</text>')

    # legend: op (shape)
    leg_y2, leg_x2 = legend2Y, ML
    seen_ops = []
    for p in points:
        k = (p["op"], p["call"])
        if k not in seen_ops:
            seen_ops.append(k)
    for op, call in seen_ops:
        shape = op_call_marker(op, call)
        label = op_call_label(op, call)
        svg.append(marker_svg(shape, leg_x2 + 6, leg_y2 - 4, TEXT_MUTED))
        svg.append(f'<text x="{leg_x2+20}" y="{leg_y2}" font-size="12" fill="{TEXT_SEC}">{label}</text>')
        leg_x2 += 20 + 8 * len(label) + 22

    svg.append(f'<text x="{ML}" y="{footnoteY}" font-size="10.5" fill="{TEXT_MUTED}">'
               'Gray dashed lines: idealized 1-vector-MAC-instr/cycle ceiling and its ridge point (too optimistic -- see doc/gem5_integration.md). '
               'Blue dashed lines: empirically-measured FloatSimd FU ceiling and its ridge point (authoritative).</text>')
    svg.append(f'<text x="{ML}" y="{footnote2Y}" font-size="10.5" fill="{TEXT_MUTED}">'
               'Points nudged a few px apart within each arithmetic-intensity cluster for legibility -- '
               'FULLY_CONNECTED and both LSTM calls share the exact same AI (2.00 FLOP/byte).</text>')

    svg.append('</svg>')
    return "\n".join(svg)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--log", default=DEFAULT_LOG, help=f"roofline_log.txt to read (default: {DEFAULT_LOG})")
    parser.add_argument("--out", default=DEFAULT_OUT, help=f"SVG output path (default: {DEFAULT_OUT})")
    args = parser.parse_args()

    if not os.path.exists(args.log):
        sys.exit(
            f"error: {args.log} not found -- run script/4_roofline_report.py "
            "first to generate it"
        )

    meta, ai_rows, perf_rows = parse_report(args.log)
    points = build_points(ai_rows, perf_rows)
    if not points:
        sys.exit(f"error: no plottable (AI, GFLOP/s) points found in {args.log}")

    svg = render_svg(meta, points)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(svg)
    print(f"wrote {args.out} ({len(points)} points, ceiling={meta.get('ceiling_gflops')} GFLOP/s)")


if __name__ == "__main__":
    main()
