#!/usr/bin/env python3
"""Generate the static roofline SVG for doc/dtln/performance_dtln.md, parsing
doc/dtln/roofline_log.txt instead of hardcoding the data points -- unlike
the sibling gemm project's script/gen_roofline_svg.py (which hand-codes a
SERIES/POINTS table refreshed by copy-paste after each sweep), this one
reads script/4_roofline_report.py's own output directly, so re-running
that report and this script back-to-back always plots the current numbers
with no manual transcription step.

No external deps (pure stdlib `math` + string building), same reasoning
as the gemm version: renders inline on GitHub as a plain image, no
matplotlib/cairosvg needed, dependency-free for anyone re-running this
later.

Usage:
  python3 /home/ajno5/work/2_pattern/tflm/script/5_gen_roofline_svg.py
  python3 /home/ajno5/work/2_pattern/tflm/script/5_gen_roofline_svg.py \\
      --log /path/to/other_roofline_log.txt --out /path/to/out.svg

To refresh after a new run: `python3 script/4_roofline_report.py` (writes
doc/dtln/roofline_log.txt), then this script -- no data to hand-edit.
"""
import argparse
import math
import os
import re
import sys
from collections import defaultdict

PROJECT_ROOT = "/home/ajno5/work/2_pattern/tflm"
DEFAULT_LOG = os.path.join(PROJECT_ROOT, "doc", "dtln", "roofline_log.txt")
DEFAULT_OUT = os.path.join(PROJECT_ROOT, "doc", "dtln", "dtln_roofline.svg")

TABLE_ROW_RE = re.compile(r"^\|(.+)\|\s*$")


# ---------------------------------------------------------------------------
# Parse doc/dtln/roofline_log.txt (script/4_roofline_report.py's output).
# ---------------------------------------------------------------------------


def parse_cell(s):
    s = s.strip()
    return s


def parse_table(lines, start_idx):
    """lines[start_idx] is the table's header row ('| col | col | ... |').
    Returns (header_cells, data_rows, next_idx) -- next_idx is the line
    index right after the last row of this table."""
    header = [parse_cell(c) for c in lines[start_idx].strip().strip("|").split("|")]
    i = start_idx + 1
    if i < len(lines) and set(lines[i].strip()) <= set("|-: "):
        i += 1  # skip the '|---|---|' separator row
    rows = []
    while i < len(lines) and TABLE_ROW_RE.match(lines[i]):
        cells = [parse_cell(c) for c in lines[i].strip().strip("|").split("|")]
        rows.append(dict(zip(header, cells)))
        i += 1
    return rows, i


def clean_number(s):
    """'0.05%' -> 0.05, '1,234.56' -> 1234.56, '`FULLY_CONNECTED`' -> FULLY_CONNECTED (non-numeric passthrough)."""
    s = s.strip().strip("`")
    t = s.replace(",", "").rstrip("%")
    try:
        return float(t)
    except ValueError:
        return s


def parse_report(log_path):
    with open(log_path) as f:
        lines = f.read().splitlines()

    meta = {}
    m = re.search(r"^Model: (\S+)$", "\n".join(lines), re.MULTILINE)
    if m:
        meta["model_name"] = os.path.splitext(os.path.basename(m.group(1)))[0]
    m = re.search(r"peak BW ([\d.]+) GB/s", "\n".join(lines))
    if m:
        meta["peak_bw_gbps"] = float(m.group(1))
    m = re.search(r"idealized peak compute ([\d.]+) GFLOP/s", "\n".join(lines))
    if m:
        meta["peak_compute_gflops"] = float(m.group(1))
    m = re.search(r"ridge point ([\d.]+) FLOP/byte", "\n".join(lines))
    if m:
        meta["ridge_point"] = float(m.group(1))
    m = re.search(r"Empirical compute-roof ceiling: ([\d.]+) GFLOP/s", "\n".join(lines))
    if m:
        meta["ceiling_gflops"] = float(m.group(1))
    m = re.search(r"Empirical fc_bottleneck warm-cache ceiling: ([\d.]+) GFLOP/s", "\n".join(lines))
    if m:
        meta["fc_warm_ceiling_gflops"] = float(m.group(1))
    m = re.search(r"Empirical cold-cache ceiling: ([\d.]+) GFLOP/s", "\n".join(lines))
    if m:
        meta["cold_ceiling_gflops"] = float(m.group(1))

    ai_rows, perf_rows = [], []
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("### Arithmetic intensity"):
            j = i + 1
            while j < len(lines) and not lines[j].startswith("|"):
                j += 1
            ai_rows, i = parse_table(lines, j)
            continue
        if line.startswith("### Achieved performance"):
            j = i + 1
            while j < len(lines) and not lines[j].startswith("|"):
                j += 1
            perf_rows, i = parse_table(lines, j)
            continue
        i += 1

    if not meta or not ai_rows or not perf_rows:
        sys.exit(
            f"error: couldn't find expected sections in {log_path} -- "
            "was it generated by script/4_roofline_report.py?"
        )
    return meta, ai_rows, perf_rows


def build_points(ai_rows, perf_rows):
    """Join the two tables on (op, call) -> [(op, call, variant, ai, gflops), ...]."""
    ai_by_key = {}
    for row in ai_rows:
        key = (row["op"].strip("`"), row["call"])
        ai = clean_number(row["AI (FLOP/byte)"].split()[0])  # "2.00 (memory-bound)" -> 2.00
        ai_by_key[key] = ai

    points = []
    for row in perf_rows:
        key = (row["op"].strip("`"), row["call"])
        if key not in ai_by_key:
            continue  # e.g. LOGISTIC -- no FLOP model, not plottable
        p_mflops = clean_number(row["P (MFLOP/s)"])
        if not isinstance(p_mflops, float):
            continue  # "n/a (no FLOP model for this op)"
        points.append({
            "op": key[0],
            "call": key[1],
            "variant": row["variant"],
            "ai": ai_by_key[key],
            "gflops": p_mflops / 1000.0,
        })
    return points


# ---------------------------------------------------------------------------
# SVG rendering.
# ---------------------------------------------------------------------------

# Color identifies the subitem (op+call); shape identifies scalar vs
# vectorized (2 values, plain circle/square is plenty). This is a scatter
# plot, so the dataviz skill's *all-pairs* CVD check applies (any two
# marks can end up neighbors), not just the adjacent-pair check -- that
# caps a fixed-hue categorical palette at 3 series (palette.md's slots
# 1-3 are the only ones that clear all-pairs in both modes). dtln's 3
# distinct (op,call) subitems fit that exactly. A model with more
# subitems than that (e.g. anomaly_detection's 10 sequential
# FULLY_CONNECTED calls) exceeds the categorical cap, but call index is
# itself an ordered position (layer depth), so it gets an *ordinal*
# treatment instead. palette.md's single-hue blue ramp technically
# covers this, but at 10 steps its adjacent CVD separation collapses
# (light->dark blue steps sit ~2-3 dE apart in OKLab, well under the
# skill's 8 target) -- distinguishable in a legend swatch, not as loose
# scatter points. Swapped for a warm-orange -> cool-blue sweep instead:
# palette.md's slot-2 orange (#eb6834) and slot-1 blue (#2a78d6)
# endpoints, interpolated in OKLCH along the shorter hue arc (through
# red/magenta/violet, not green) with a small alternating lightness
# zigzag on top of the monotone L trend so neighbors don't just differ
# by hue -- computed via the standard sRGB<->OKLab conversion (Bjorn
# Ottosson), not eyeballed. Verified: worst adjacent AND worst all-pairs
# OKLab dE*100 both ~9.0 (clears this skill's >=8 CVD target), min
# contrast 3.25:1 on the #fcfcfb light surface (clears the >=3:1 mark
# floor) -- see doc/anomaly_detection notes for the generating script.
CATEGORICAL_COLORS = ["#2a78d6", "#eb6834", "#1baf7a"]  # palette.md slots 1-3 (blue/orange/aqua)

ORDINAL_RAMP = [  # warm orange -> cool blue, OKLCH-interpolated (light->dark call order)
    "#e76530", "#c53b3c", "#dd5274", "#b03175", "#be50a8",
    "#8c369f", "#8f57cb", "#5a40b5", "#4e63d4", "#004daf",
]

VARIANT_SHAPES = {
    "scalar": "circle",
    "vectorized": "square",
}


def ordered_subitems(points):
    """[(op, call), ...] in first-seen order -- the stable order every
    color/legend/jitter assignment below is keyed against."""
    seen = []
    for p in points:
        k = (p["op"], p["call"])
        if k not in seen:
            seen.append(k)
    return seen


def assign_subitem_colors(subitems):
    """{(op, call): hex, ...} -- categorical (3-color cap) if there are
    <=3 distinct subitems, else the ordinal ramp. Beyond len(ORDINAL_RAMP)
    (10) subitems, steps repeat -- no chart this project produces has hit
    that yet; a real 11th+ series should fold into "Other" or facet
    instead (see the dataviz skill), not silently reuse a color here."""
    n = len(subitems)
    if n <= len(CATEGORICAL_COLORS):
        return {k: CATEGORICAL_COLORS[i] for i, k in enumerate(subitems)}
    step = (len(ORDINAL_RAMP) - 1) / max(n - 1, 1)
    return {k: ORDINAL_RAMP[round(i * step) % len(ORDINAL_RAMP)] for i, k in enumerate(subitems)}


def op_call_label(op, call, compact):
    """compact=True when every point in the plot shares the same op (e.g.
    anomaly_detection's 10 FULLY_CONNECTED calls) -- the op name is then
    redundant across every legend entry, so just "call N" instead, short
    enough that a 10-entry legend still fits."""
    if compact:
        return f"call {call}"
    if op == "FULLY_CONNECTED":
        return "FULLY_CONNECTED"
    return f"LSTM (call {call})"


def marker_svg(shape, cx, cy, color, r=7):
    if shape == "diamond":
        rr = r + 1
        pts = f"{cx:.1f},{cy-rr:.1f} {cx+rr:.1f},{cy:.1f} {cx:.1f},{cy+rr:.1f} {cx-rr:.1f},{cy:.1f}"
        return f'<polygon points="{pts}" fill="{color}" stroke="#ffffff" stroke-width="1.5"/>'
    elif shape == "square":
        s = r * 1.6
        return (f'<rect x="{cx-s/2:.1f}" y="{cy-s/2:.1f}" width="{s:.1f}" height="{s:.1f}" '
                f'fill="{color}" stroke="#ffffff" stroke-width="1.5"/>')
    else:
        return f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r}" fill="{color}" stroke="#ffffff" stroke-width="1.5" opacity="0.85"/>'


JITTER_PX = 9


def compute_x_jitter(points):
    """dtln's FULLY_CONNECTED and both UNIDIRECTIONAL_SEQUENCE_LSTM calls
    all land at exactly the same AI (2.00 FLOP/byte -- see
    doc/dtln/performance_dtln.md's "Arithmetic intensity" table, not a
    coincidence: every one of these is a batch-1 int8 GEMV with zero
    weight reuse). Plotted at their true x they'd stack directly on top of
    each other and the later-drawn marker would fully hide the earlier one
    regardless of transparency, since their y values (achieved GFLOP/s) are
    also close. Nudges each op a few px apart horizontally so all three
    stay visible -- {(op, call): x_offset_px, ...}, deterministic by
    (op, call) sort order so it's stable across runs."""
    by_opcall_ai = {}
    for p in points:
        by_opcall_ai[(p["op"], p["call"])] = p["ai"]

    buckets = defaultdict(list)
    for key, ai in by_opcall_ai.items():
        buckets[round(ai, 6)].append(key)

    jitter = {}
    for ai, keys in buckets.items():
        keys = sorted(keys)
        n = len(keys)
        for idx, key in enumerate(keys):
            jitter[key] = (idx - (n - 1) / 2) * JITTER_PX
    return jitter


LEGEND_ROW_H = 22


def render_legend_row(entries, start_x, start_y, max_x, text_color, row_h=LEGEND_ROW_H):
    """entries: [(marker_fn(cx, cy) -> svg str, label), ...]. Wraps to a new
    row (start_x again, y += row_h) whenever the next entry would cross
    max_x -- shared by both legends below so a >3-subitem legend (e.g.
    anomaly_detection's 10 calls) doesn't run off the canvas. Returns
    (svg_lines, end_y) so the caller can lay out whatever comes after."""
    svg, x, y = [], start_x, start_y
    for marker_fn, label in entries:
        width = 20 + 8 * len(label) + 22
        if x + width > max_x and x > start_x:
            x, y = start_x, y + row_h
        svg.append(marker_fn(x + 6, y - 4))
        svg.append(f'<text x="{x+20}" y="{y}" font-size="12" fill="{text_color}">{label}</text>')
        x += width
    return svg, y


def render_svg(meta, points):
    W = 900
    ML, MR, MT = 78, 210, 40
    plotW, plotH = W - ML - MR, 440
    axisBottom = MT + plotH
    tickLabelY = axisBottom + 20
    axisTitleY = axisBottom + 40

    subitems = ordered_subitems(points)
    subitem_colors = assign_subitem_colors(subitems)
    compact_labels = len({op for op, _call in subitems}) == 1

    # Legend 2 (subitem colors) can wrap to multiple rows for models with
    # many subitems (e.g. anomaly_detection's 10 calls) -- simulate it
    # once here (same width math as the real render below) purely to
    # learn how many rows it takes, so the footnotes/canvas height below
    # can leave room for it.
    _sim_x, _sim_rows = ML, 1
    for _op, _call in subitems:
        _label = op_call_label(_op, _call, compact_labels)
        _width = 20 + 8 * len(_label) + 22
        if _sim_x + _width > (W - 20) and _sim_x > ML:
            _sim_x, _sim_rows = ML, _sim_rows + 1
        _sim_x += _width
    legend2_extra_rows = _sim_rows - 1

    legend1Y = axisBottom + 65
    legend2Y = axisBottom + 90
    footnoteY = axisBottom + 114 + legend2_extra_rows * LEGEND_ROW_H
    footnote2Y = footnoteY + 16
    footnote3Y = footnote2Y + 16
    H = footnote3Y + 16

    peak_bw = meta.get("peak_bw_gbps")
    peak_compute = meta.get("peak_compute_gflops")
    ceiling = meta.get("ceiling_gflops")
    fc_warm_ceiling = meta.get("fc_warm_ceiling_gflops")
    cold_ceiling = meta.get("cold_ceiling_gflops")
    ridge_idealized = meta.get("ridge_point")
    # The ridge point that actually matters for this project: where the
    # memory roof crosses the *measured* FU ceiling, not the idealized
    # peak-compute one -- everything left of it is memory-bound even
    # against what this CPU can genuinely sustain, which is the number
    # doc/gem5_integration.md treats as authoritative.
    ridge_measured = meta["ceiling_gflops"] / peak_bw if peak_bw and ceiling else None
    # fc_bottleneck's own warm-cache ridge point -- same op/shape/pass-count
    # as the cold-cache ceiling below, differing only in cache state, so
    # this and ridge_cold isolate exactly the cache-eviction effect.
    ridge_fc_warm = fc_warm_ceiling / peak_bw if peak_bw and fc_warm_ceiling else None
    # Cold-cache ridge point: where the memory roof crosses the cold-cache
    # ceiling instead of the warm one -- the ridge point that matters for
    # this project's *actual* single-shot workload (see "Second
    # correction" in doc/dtln/performance_dtln.md). Lower than ridge_measured,
    # since the cold ceiling itself is lower.
    ridge_cold = cold_ceiling / peak_bw if peak_bw and cold_ceiling else None

    ais = [p["ai"] for p in points]
    x_of_interest = ais + [v for v in (ridge_idealized, ridge_measured, ridge_fc_warm, ridge_cold) if v]
    gs = [p["gflops"] for p in points] + [v for v in (ceiling, fc_warm_ceiling, cold_ceiling) if v]
    x_lo = min(0.5, min(x_of_interest) / 2) if x_of_interest else 0.5
    x_hi = max(5.0, max(x_of_interest, default=10) * 2)
    y_lo = min(0.03, min(gs) / 3) if gs else 0.03
    y_hi = max(meta.get("peak_compute_gflops", 128) * 2, max(gs) * 3)

    x_dom = (x_lo, x_hi)
    y_dom = (y_lo, y_hi)
    lx, rx = math.log10(x_dom[0]), math.log10(x_dom[1])
    ly, ry = math.log10(y_dom[0]), math.log10(y_dom[1])

    def px(ai):
        return ML + (math.log10(ai) - lx) / (rx - lx) * plotW

    def py(g):
        return MT + plotH - (math.log10(g) - ly) / (ry - ly) * plotH

    def log_ticks(lo, hi):
        ticks = []
        e = math.floor(math.log10(lo))
        while 10 ** e <= hi * 1.001:
            for m in (1, 2, 3, 5):
                v = m * 10 ** e
                if lo * 0.999 <= v <= hi * 1.001:
                    ticks.append(round(v, 6))
            e += 1
        return ticks

    x_ticks = log_ticks(*x_dom)
    y_ticks = log_ticks(*y_dom)

    TEXT_MUTED = "#767671"
    TEXT_SEC = "#3d3d3a"
    TEXT_PRI = "#111111"
    GRID = "#e4e3dd"
    AXIS = "#b9b8b1"

    svg = []
    svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" font-family="Helvetica, Arial, sans-serif">')
    svg.append(f'<rect x="0" y="0" width="{W}" height="{H}" fill="#ffffff"/>')
    model_name = meta.get("model_name", "model")
    svg.append(f'<text x="{ML}" y="22" font-size="15" fill="{TEXT_PRI}" font-weight="700">{model_name} roofline: scalar vs. vectorized vs. warm/fc-warm/cold-cache ceilings</text>')

    for v in x_ticks:
        x = px(v)
        svg.append(f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{MT+plotH}" stroke="{GRID}" stroke-width="1"/>')
        label = f"{v:g}"
        svg.append(f'<text x="{x:.1f}" y="{tickLabelY}" font-size="12" fill="{TEXT_MUTED}" text-anchor="middle">{label}</text>')
    for v in y_ticks:
        y = py(v)
        svg.append(f'<line x1="{ML}" y1="{y:.1f}" x2="{ML+plotW}" y2="{y:.1f}" stroke="{GRID}" stroke-width="1"/>')
        label = f"{v:g}"
        svg.append(f'<text x="{ML-10}" y="{y+4:.1f}" font-size="12" fill="{TEXT_MUTED}" text-anchor="end">{label}</text>')

    svg.append(f'<line x1="{ML}" y1="{MT+plotH}" x2="{ML+plotW}" y2="{MT+plotH}" stroke="{AXIS}" stroke-width="1"/>')
    svg.append(f'<line x1="{ML}" y1="{MT}" x2="{ML}" y2="{MT+plotH}" stroke="{AXIS}" stroke-width="1"/>')

    svg.append(f'<text x="{ML+plotW/2:.1f}" y="{axisTitleY}" font-size="13" fill="{TEXT_SEC}" text-anchor="middle">Arithmetic intensity (FLOP / byte, log scale)</text>')
    svg.append(f'<text x="20" y="{MT+plotH/2:.1f}" font-size="13" fill="{TEXT_SEC}" text-anchor="middle" transform="rotate(-90 20 {MT+plotH/2:.1f})">Achieved performance (GFLOP/s, log scale)</text>')

    # memory-bound roof: g = peak_bw * ai
    if peak_bw:
        x1 = x_dom[0]
        x2 = min(x_dom[1], y_dom[1] / peak_bw)
        if x2 > x1:
            svg.append(f'<line x1="{px(x1):.1f}" y1="{py(peak_bw*x1):.1f}" x2="{px(x2):.1f}" y2="{py(peak_bw*x2):.1f}" '
                       f'stroke="{TEXT_MUTED}" stroke-width="2" stroke-dasharray="5 4"/>')
            svg.append(f'<text x="{px(x2)-6:.1f}" y="{py(peak_bw*x2)-8:.1f}" font-size="11.5" fill="{TEXT_SEC}" text-anchor="end">memory roof ({peak_bw} GB/s)</text>')

    # Ridge point vs. the *measured* FU ceiling -- styled bold and blue to
    # match the measured-ceiling line: this is the ridge point that
    # actually matters for this project (see doc/gem5_integration.md --
    # the idealized 128 GFLOP/s figure was the wrong ceiling to begin
    # with). Left of it, an op is memory-bound even against what this CPU
    # can genuinely sustain, not just against a too-optimistic ideal. A
    # filled dot marks the actual point -- where the memory roof crosses
    # the measured-ceiling line -- so it reads as a point, not just an
    # abstract vertical line.
    if ridge_measured and ceiling and x_dom[0] <= ridge_measured <= x_dom[1]:
        x, y = px(ridge_measured), py(ceiling)
        svg.append(f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{MT+plotH}" stroke="#2a78d6" '
                   f'stroke-width="2" stroke-dasharray="1 4"/>')
        svg.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="5" fill="#2a78d6" stroke="#ffffff" stroke-width="1.5"/>')
        svg.append(f'<text x="{x+6:.1f}" y="{axisBottom-8}" font-size="11.5" fill="#2a78d6" font-weight="700">ridge (measured), {ridge_measured:.2f} FLOP/byte</text>')

    # Ridge point vs. fc_bottleneck's own *warm-cache* ceiling -- same op,
    # shape, and single-pass count as the cold-cache ceiling below,
    # differing only in cache state (see build_report's comment in
    # script/4_roofline_report.py). Styled amber to stay distinct from the
    # int8dot warm-ceiling blue and cold-ceiling purple; label placed at
    # mid-plot height since its x is often close to ridge_measured's,
    # avoiding text collision with the bottom/top labels of the other two.
    if ridge_fc_warm and fc_warm_ceiling and x_dom[0] <= ridge_fc_warm <= x_dom[1]:
        x, y = px(ridge_fc_warm), py(fc_warm_ceiling)
        svg.append(f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{MT+plotH}" stroke="#c98500" '
                   f'stroke-width="2" stroke-dasharray="1 4"/>')
        svg.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="5" fill="#c98500" stroke="#ffffff" stroke-width="1.5"/>')
        svg.append(f'<text x="{x+6:.1f}" y="{MT+plotH/2:.1f}" font-size="11.5" fill="#c98500" font-weight="700">ridge (fc warm), {ridge_fc_warm:.2f} FLOP/byte</text>')

    # Ridge point vs. the *cold-cache* ceiling -- the ridge point that
    # matters for this project's actual achieved-performance points below,
    # since dtln_test's single Invoke() call never gets a warm cache (see
    # "Second correction" in doc/dtln/performance_dtln.md). Styled purple to
    # stay visually distinct from the warm-measured blue and idealized
    # gray lines while still reading as "the important one" (bold, solid
    # dot) rather than the idealized line's muted treatment.
    if ridge_cold and cold_ceiling and x_dom[0] <= ridge_cold <= x_dom[1]:
        x, y = px(ridge_cold), py(cold_ceiling)
        svg.append(f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{MT+plotH}" stroke="#7c5cbf" '
                   f'stroke-width="2" stroke-dasharray="1 4"/>')
        svg.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="5" fill="#7c5cbf" stroke="#ffffff" stroke-width="1.5"/>')
        svg.append(f'<text x="{x+6:.1f}" y="{MT+28}" font-size="11.5" fill="#7c5cbf" font-weight="700">ridge (cold-cache), {ridge_cold:.2f} FLOP/byte</text>')

    # Ridge point vs. the idealized peak-compute roof -- kept for contrast,
    # styled muted/secondary (same idealized-vs-measured distinction as the
    # two roof lines below), dot at the same memory-roof/ceiling
    # intersection logic.
    if ridge_idealized and peak_compute and x_dom[0] <= ridge_idealized <= x_dom[1]:
        x, y = px(ridge_idealized), py(peak_compute)
        svg.append(f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{MT+plotH}" stroke="{AXIS}" '
                   f'stroke-width="1.5" stroke-dasharray="1 4"/>')
        svg.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="5" fill="{AXIS}" stroke="#ffffff" stroke-width="1.5"/>')
        svg.append(f'<text x="{x+6:.1f}" y="{MT+14}" font-size="11" fill="{TEXT_MUTED}">ridge (idealized), {ridge_idealized:g} FLOP/byte</text>')

    # idealized peak-compute roof (the naive, too-optimistic ceiling -- kept for contrast)
    if peak_compute and y_dom[0] <= peak_compute <= y_dom[1]:
        y = py(peak_compute)
        svg.append(f'<line x1="{ML}" y1="{y:.1f}" x2="{ML+plotW}" y2="{y:.1f}" stroke="{AXIS}" '
                   f'stroke-width="1.5" stroke-dasharray="2 5" opacity="0.8"/>')
        svg.append(f'<text x="{ML+plotW+8}" y="{y+4:.1f}" font-size="11" fill="{TEXT_MUTED}">idealized {peak_compute:g} GFLOP/s</text>')

    # empirically-measured FU ceiling, warm cache (int8dot_ceiling.c) --
    # correct for "how fast could this FU go if data were already cached",
    # but not the ceiling this project's actual achieved-performance
    # points below can be measured against -- see the cold-cache line.
    if ceiling and y_dom[0] <= ceiling <= y_dom[1]:
        y = py(ceiling)
        svg.append(f'<line x1="{ML}" y1="{y:.1f}" x2="{ML+plotW}" y2="{y:.1f}" stroke="#2a78d6" '
                   f'stroke-width="2.5" stroke-dasharray="2 4"/>')
        svg.append(f'<text x="{ML+plotW+8}" y="{y+4:.1f}" font-size="11.5" fill="#2a78d6" font-weight="700">{ceiling:g} GFLOP/s measured (warm)</text>')

    # fc_bottleneck's own empirically-measured warm-cache ceiling
    # (FC_VARIANT=4 FC_CACHE_MODE=0) -- same op/shape/pass-count as the
    # cold-cache line below, differing only in cache state, so the vertical
    # gap between this line and the cold one isolates exactly the
    # cache-eviction cost. Its value (often close to the int8dot warm
    # ceiling above) can land within a few px of that line's label, so the
    # label is nudged down to stay legible.
    if fc_warm_ceiling and y_dom[0] <= fc_warm_ceiling <= y_dom[1]:
        y = py(fc_warm_ceiling)
        svg.append(f'<line x1="{ML}" y1="{y:.1f}" x2="{ML+plotW}" y2="{y:.1f}" stroke="#c98500" '
                   f'stroke-width="2" stroke-dasharray="2 4"/>')
        svg.append(f'<text x="{ML+plotW+8}" y="{y+16:.1f}" font-size="11.5" fill="#c98500" font-weight="700">{fc_warm_ceiling:g} GFLOP/s measured (fc warm)</text>')

    # empirically-measured cold-cache ceiling (fc_bottleneck.c,
    # FC_VARIANT=4 FC_CACHE_MODE=1) -- the ceiling that actually applies to
    # this project's achieved-performance points below, since dtln_test's
    # single Invoke() call never gets a warm cache. Solid, not dashed, and
    # drawn last (on top) to read as the authoritative line -- see "Second
    # correction" in doc/dtln/performance_dtln.md.
    if cold_ceiling and y_dom[0] <= cold_ceiling <= y_dom[1]:
        y = py(cold_ceiling)
        svg.append(f'<line x1="{ML}" y1="{y:.1f}" x2="{ML+plotW}" y2="{y:.1f}" stroke="#7c5cbf" '
                   f'stroke-width="2.5"/>')
        svg.append(f'<text x="{ML+plotW+8}" y="{y+4:.1f}" font-size="11.5" fill="#7c5cbf" font-weight="700">{cold_ceiling:g} GFLOP/s measured (cold)</text>')

    # scatter points -- color = subitem (op+call), shape = scalar/vectorized
    jitter = compute_x_jitter(points)
    for p in points:
        cx = px(p["ai"]) + jitter.get((p["op"], p["call"]), 0)
        cy = py(p["gflops"])
        color = subitem_colors.get((p["op"], p["call"]), TEXT_MUTED)
        shape = VARIANT_SHAPES.get(p["variant"], "circle")
        svg.append(marker_svg(shape, cx, cy, color))

    # legend: variant (shape) -- always 2 entries, never wraps
    leg_y, leg_x = legend1Y, ML
    for variant, shape in VARIANT_SHAPES.items():
        svg.append(marker_svg(shape, leg_x + 6, leg_y - 4, TEXT_MUTED, r=6))
        svg.append(f'<text x="{leg_x+20}" y="{leg_y}" font-size="12" fill="{TEXT_SEC}">{variant}</text>')
        leg_x += 20 + 8 * len(variant) + 22
    svg.append(f'<line x1="{leg_x}" y1="{leg_y-5}" x2="{leg_x+20}" y2="{leg_y-5}" stroke="{TEXT_MUTED}" stroke-width="2" stroke-dasharray="4 3"/>')
    svg.append(f'<text x="{leg_x+26}" y="{leg_y}" font-size="12" fill="{TEXT_SEC}">Memory roof</text>')

    # legend: subitem (color) -- may wrap to multiple rows (e.g.
    # anomaly_detection's 10 calls); the layout-height computation above
    # already reserved room for however many rows this takes.
    entries = [
        (lambda cx, cy, c=subitem_colors[k]: marker_svg("circle", cx, cy, c),
         op_call_label(k[0], k[1], compact_labels))
        for k in subitems
    ]
    legend2_svg, _legend2_end_y = render_legend_row(entries, ML, legend2Y, W - 20, TEXT_SEC)
    svg.extend(legend2_svg)

    svg.append(f'<text x="{ML}" y="{footnoteY}" font-size="10.5" fill="{TEXT_MUTED}">'
               'Gray dashed lines: idealized 1-vector-MAC-instr/cycle ceiling (too optimistic). '
               'Blue dashed lines: warm-cache FU ceiling (int8dot_ceiling.c -- correct FU throughput, but data is never actually this cached).</text>')
    svg.append(f'<text x="{ML}" y="{footnote2Y}" font-size="10.5" fill="{TEXT_MUTED}">'
               'Amber dashed lines: fc_bottleneck.c warm-cache ceiling (FC_CACHE_MODE=0) -- same op/shape/pass-count as the purple cold-cache line, differing only in cache state. '
               f'Purple solid line: cold-cache ceiling (FC_CACHE_MODE=1) -- the ceiling that actually applies here, since {model_name}\'s single Invoke() call reads every weight tensor exactly once, never cached.</text>')
    svg.append(f'<text x="{ML}" y="{footnote3Y}" font-size="10.5" fill="{TEXT_MUTED}">'
               'Points nudged a few px apart within each arithmetic-intensity cluster for legibility -- '
               'every batch-1 FULLY_CONNECTED/LSTM call shares the exact same AI (2.00 FLOP/byte).</text>')

    svg.append('</svg>')
    return "\n".join(svg)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--log", default=DEFAULT_LOG, help=f"roofline_log.txt to read (default: {DEFAULT_LOG})")
    parser.add_argument("--out", default=DEFAULT_OUT, help=f"SVG output path (default: {DEFAULT_OUT})")
    args = parser.parse_args()

    if not os.path.exists(args.log):
        sys.exit(
            f"error: {args.log} not found -- run script/4_roofline_report.py "
            "first to generate it"
        )

    meta, ai_rows, perf_rows = parse_report(args.log)
    points = build_points(ai_rows, perf_rows)
    if not points:
        sys.exit(f"error: no plottable (AI, GFLOP/s) points found in {args.log}")

    svg = render_svg(meta, points)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(svg)
    print(f"wrote {args.out} ({len(points)} points, ceiling={meta.get('ceiling_gflops')} "
          f"GFLOP/s warm, {meta.get('fc_warm_ceiling_gflops')} GFLOP/s fc warm, "
          f"{meta.get('cold_ceiling_gflops')} GFLOP/s cold)")


if __name__ == "__main__":
    main()
